### ISSUE TITLE
Support unspecified height and width input shape for segmentation models

### ISSUE THREAD

**Issue by alekseisolovev** [keras-team/keras-cv#1229]
Current DeepLabV3 implementation does not support `(None, None, 3)` input shape:
```
ValueError: Input shapes for both the backbone and DeepLabV3 are `None`.
```
Segmentation models are able to be trained on image crops and evaluated on full images, therefore unspecified height and width input shape is required. For example, [here](https://github.com/qubvel/segmentation_models) is an existing implementation that supports this.

**Comment by innat** [comment]
Can you check these 
https://github.com/keras-team/keras-cv/issues/1081#issuecomment-1365646179

**Comment by alekseisolovev** [comment]
Thanks, but if I adjust an input shape of a backbone it becomes a predefined input shape for a segmentation model. What I'm looking for is this:
![Screenshot from 2023-01-03 17-35-00](https://user-images.githubusercontent.com/23499324/210400309-fd96713d-a77f-4534-a8a7-53fbb10c01d6.png)

**Comment by DavidLandup0** [comment]
Thanks for the issue!

DeepLabV3 has to have at least one specified input shape because the `Upsampling` layers depend on the shape at initialization time. It inherits the input shape from the backbone model by default. UNet doesn't have this constraint because both downsampling and upsampling is done via convolutions.

Does this prevent proper usage for a task?

**Comment by alekseisolovev** [comment]
I see, thanks! It works but with some limitations.
