### ISSUE TITLE
Adding flexibility to the as_backbone API

### ISSUE THREAD

**Issue by quantumalaviya** [keras-team/keras-cv#1245]
This is the issue, originally shared by @DavidLandup0 in #1232: 

> In a previous PR, I was trying to use ResNetV2's as_backbone() but the issue was that I could not select the specific layers (only a range). The range had two issues:
> 
> Unused layers (only needed the first and last, middle ones added params but weren't used)
> The final output had 2048 channels (while the paper used a few layers earlier to limit the channels to 256 to reduce the effect of the feature maps when added to another stage)
> It's great that we can have as_backbone() as a general util instead of a method in each model. To make it more globally usable (and the default approach to exposing backbones) - should we maybe allow for layer_names=('l1', 'l2', ...) instead of a range?

Following is a possible approach that I suggested in the same PR:

> I agree with David. I think the API should be updated to something like this:
> 
> as_backbone(levels=None)
> Where levels is one of:
> 
> a tuple of size 2 indictating a range which would work as it does currently. None at any one of the indices would imply the limit for that level. For example, (None, 5) would mean levels 3, 4, 5 for a backbone where 2 is the minimum level.
> a list of strings that have all the layer names required in the output.
> Defaults to None which includes all levels from _backbone_level_outputs.
> 
> Ofc, this API would need some refining but maybe its a better alternative? I also wonder if this util is should even be exposed or kept as an internal util.

Opening this issue to discuss this as the PR has been merged.

**Comment by DavidLandup0** [comment]
Thanks for bringing this up!
I agree with the idea. The `as_backbone()` method is a brilliant idea that we definitely want to give users, and separating it as a KCV util instead of a method is a general way to provide KCV models as backbones (a major usage of these archs).

That being said, the current API exposes sometimes unusable layers (for instance, if you only need the first and last spatial level, all of the middle ones just amp up the params) and layers with a channel count that makes it harder to work with the feature maps (such as 2048 in ResNet's case). Adding just a bit more flexibility here would go a long way to allow users to:

- Rely on KCV models for backbones
- Supply their own models built using Keras/TF or KCV components
- Stay in the ecosystem without external dependencies
- Allow for reasonable defaults that just work (a thing Keras does wonderfully IMO), while also allowing for lower-level customization

I agree that layer names are uglier than "levels=[1, 3]", but one could argue that layer names are a lot less ambiguous than level names. Ideally, we could aim to provide both - supply levels if you don't want to think about the structure, supply names if you know exactly what you want?

> how do expect users to find those layer names -- this can sometimes be trivial, but sometimes quite some manual work

A `summary()` call is typically fine, especially if `expand_nested=True`. Sometimes, layers hide other layers, such as with MBConvBlock, in which case it's a bit trickier, but even with them, we could unravel the layers internally to allow people to explore the structure. We could look into providing a util such as `inspect_model()` to list out hidden layer names for this purpose.

> would the output be string -> output_tensor, and how does that interact with our FPN / Detection / Segmentation models which today only accept int?

I like the idea of a dict output, because it allows for multiple spatial levels, so we could do something like:

```
output = utils.as_backbone(backbone) # {'1': x, '2': y}
seg_head(output) 
```

It's ordered and can tie names with output values. This would work both for ranges and specific layers that are requested.

**Comment by ianstenbit** [comment]
The `as_backbone` API has been replaced with the Backbone+Task architecture, so this is now obsolete
