### ISSUE TITLE
Use a max line length of 80 universally, and allowlist docstrings with `# noqa: E501`

### ISSUE THREAD

**Issue by ianstenbit** [keras-team/keras-cv#1532]
See conversation in #1509.

This should essentially just require that we switch our linter config to universally enforce 80 chars/line, and add the `# noqa: E501` tag to all docstrings > 80 chars wide.

**Comment by haifeng-jin** [comment]
For long lines of URLs in the docstrings, we should tag them with `# noqa: E501`.

For other types of long lines that can be adjusted, we should just adjust them. They exist in the codebase because we did not enforce 80 char for a while. So some PRs with other long lines also got merged.

The PR should also change the `max-line-length` to 80 from 200 in `setup.cfg`.

**Comment by ID6109** [comment]
The `max-line-length` is already set to 80. Should the `max-doc-length` be changed from 200 to 80? W505 errors will be introduced then.

**Comment by haifeng-jin** [comment]
After #1509 is merged, the `max-line-length` will be 200 and `max-doc-length` will be removed.

**Comment by ID6109** [comment]
I'll submit a PR by tomorrow

**Comment by ID6109** [comment]
I've noticed multiple spaces being used for the following line after the period of the preceding line. Is this part of the code style?
