### ISSUE TITLE
(On Hold) Color Augmentation

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#164]
# Apply the Lookup Table to the Image

( Skeptical about this processing layer. I better post this to [discussion](https://github.com/keras-team/keras-cv/discussions/93) but the activity there seems limited. )

Post: https://github.com/deepmind/multidim-image-augmentation/blob/master/doc/color_augmentation_colab.md

![image](https://user-images.githubusercontent.com/17668390/156923735-c06d43e4-323d-4f47-a7b5-2d966006bd3d.png)

**Comment by LukeWood** [comment]
The KerasCV team is attempting to narrow the package scope in order to more efficiently use our limited resources. As such, we are only accepting contributions directly related to items on the 6 month roadmap for the package.

If you feel this feature could be particularly useful, or would like to contribute it - please feel free to re-open this issue and ping LukeWood, ianstenbit or tanzhenyu

Feel free to read more on the roadmap:
https://github.com/keras-team/keras-cv/blob/master/.github/ROADMAP.md
