### ISSUE TITLE
Train imagenet weights for `MobileNetV3`

### ISSUE THREAD

**Issue by jbischof** [keras-team/keras-cv#1741]
We currently have no pretrained weights for one of our most important backbones, MobileNet. Let's use our training script to produce one ([link](https://github.com/keras-team/keras-cv/tree/master/examples/training/classification/imagenet)).

Note: Before migration to the new API (#1641), MobileNet had a custom classification head. We should consider add a new task in addition to `ImageClassifier` if this is needed to get optimal performance.

**Comment by ianstenbit** [comment]
Quick update on this: we've now pre-trained the `Large` variant on ImageNet with reasonable results (using a dense classification head, so the classifier part isn't outstanding but the backbone should be good).

After some hyperparameter tuning,  I think I now also have a decent `Small` variant training run going. Should complete in a couple days.

**Comment by jbischof** [comment]
@ianstenbit should we consider making a `MobileNetClassifier` with the correct head? Would be quite lightweight and could also accept any backbone as a preset.

**Comment by jbischof** [comment]
@ianstenbit how did mobilenet small work out?

**Comment by ianstenbit** [comment]
Small version results were not great -- I am kicking off a few more training runs now. Benchmark paper result is [67% top-1 on ImageNet](https://arxiv.org/pdf/1905.02244.pdf), but we'd expect to get a bit lower since we're just using a Dense Head.

If this continues to be an issue then yes I'll just make a separate `MobileNetClassifier` head.
