### ISSUE TITLE
Porting DeepVision into KerasCV

### ISSUE THREAD

**Issue by DavidLandup0** [keras-team/keras-cv#1933]
Hey team! Absolutely stellar work on Core Keras, and bringing it to KCV!

Since one of the main tennets of my own lib, [DeepVision](https://github.com/DavidLandup0/deepvision) , was to unify computer vision through a back-end agnostic high-level API with interchangeable modular components - and this is exactly what Core Keras is, I'd like to re-route the layer and models from there to here.

It's got a few flavors of transformer encoders, several flavors of attention, on-the-fly weight porting, as well as SAM and CLIP (almost pushed to main).

Are there plans to add any of these to KCV soon? I'd personally port all of these.

@jbischof @ianstenbit

**Comment by ianstenbit** [comment]
Hey @DavidLandup0 -- I would be stoked to have you bring these components over to KerasCV!

These are all things that we'd love to include in KerasCV, and I would be happy to help with reviewing ports. I think @tirthasheshpatel has also done some work on SAM and would be interested in that piece.

Transformer components, CLIP, and SAM are all things that are in our roadmap but that we don't currently have the eng time to implement, so that would be fantastic. 🚀 

I'm happy to discuss further over a call, or feel free to just start opening some PRs and tagging me -- I will prioritize taking a look at those.

**Comment by DavidLandup0** [comment]
Thanks for the prompt response @ianstenbit!
It may make sense to coordinate this a bit instead of just opening lots of PRs on my end. The APIs are fairly compatible, but there are nuances in layers and implementations that may be worth ironing out and syncing on.

Let's set up a group call to sync up? I can get started on these tomorrow.

**Comment by ianstenbit** [comment]
> Thanks for the prompt response @ianstenbit! It may make sense to coordinate this a bit instead of just opening lots of PRs on my end. The APIs are fairly compatible, but there are nuances in layers and implementations that may be worth ironing out and syncing on.
> 
> Let's set up a group call to sync up? I can get started on these tomorrow.

Sounds good -- I sent you an invite for tomorrow afternoon, but feel free to suggest a different time!

**Comment by IMvision12** [comment]
This is really awesome!! Let me know if you need a helping hand :) @DavidLandup0

**Comment by sachinprasadhs** [comment]
Hi, The linked PR is already merged here https://github.com/keras-team/keras-cv/pull/1946, could you please close the issue if there is no pending action to be taken.
