### ISSUE TITLE
Facing error in import [Colab Notebook]

### ISSUE THREAD

**Issue by cosmo3769** [keras-team/keras-cv#1989]
**Running in colab.**

I am getting a strange error here when I am using `git clone` for keras-cv and `pip install` for keras-core. 

```
!pip install -qq git+https://github.com/keras-team/keras-core
!git clone https://github.com/keras-team/keras-cv.git

import keras_cv
import keras_core
```

Also, using `pip install` for both sometimes works fine and sometimes don't and give the same error as previous one.

Here is the error:

<img width="692" alt="Screenshot 2023-07-28 at 6 46 58 PM" src="https://github.com/keras-team/keras-cv/assets/53268607/9cd0c8de-9cb7-4741-95b3-013f8963f514">

Am I missing something?

**Comment by NiharJani2002** [comment]
@cosmo3769 

Set The Backend because if we look at the Keras-core GitHub repo, they have mentioned configuring the backend.
![image](https://github.com/keras-team/keras-cv/assets/84491997/09af0402-b490-4ad4-a0b0-742da9d3b880)


Keras-Core Github Link: https://github.com/keras-team/keras-core/tree/main

**Comment by cosmo3769** [comment]
Thanks, I used this as well. But it was not working. I checked it again. I was making a mistake. When I was using `git clone`, I was not installing the package of keras-cv too. Installing this fixed it.
