### ISSUE TITLE
Add a new argument `ignore_classes` to `keras_cv.visualization.plot_bounding_box_gallery()`

### ISSUE THREAD

**Issue by VachanVY** [keras-team/keras-cv#1997]
**Adding a new argument `ignore_classes` to `keras_cv.visualization.plot_bounding_box_gallery()` is helpful for object detection models like `DETR`** 
(context: The [DETR](https://arxiv.org/abs/2005.12872) object detection model is designed to infer a fixed-size set of `N` predictions, where `N` is significantly larger than the typical number of objects present in an image, as not all images have `N` objects we pad classes and boxes with `0 (no_object class)` and `[0,0,0,0]`). 
### So ignore classes (specifically for `no_object` class) and corresponding boxes given in argument `ignore_classes`

**Comment by innat** [comment]
> DETR where the classes and boxes are padded with 0 and [0,0,0,0]

Could you please elaborate on it? Do you mean background or no object stuff!
FYI, in keras-cv, I think class labels are zero-indexed.

**Comment by VachanVY** [comment]
The [DETR](https://arxiv.org/abs/2005.12872) object detection model is designed to infer a fixed-size set of `N` predictions, where `N` is significantly larger than the typical number of objects present in an image.
So for example suppose `N=10`, and the number of objects in the image is 2, the classes vector (shape: (2)) and box matrix (shape: (2, 4)) is padded to shape (N,) and (N, 4) respectively.

So while plotting using `keras_cv.visualization.plot_bounding_box_gallery()` it'll be helpful if it had an argument `ignore_classes` which takes a list of classes that we don't want it to plot as the bounding boxes

**Comment by VachanVY** [comment]
@LukeWood @innat Please check, it's actually helpful during inference, especially in the case of DETR object detection model

**Comment by ianstenbit** [comment]
Hey @VachanVY  -- we actually already support masking for bounding box visualization!

KerasCV standardizes on using a class of `-1` for padded boxes like what you've described, and boxes with a class of `-1` passed to the visualization utility won't be rendered!

Since `-1` is the standard throughout KerasCV, I think it's best not to include an option to ignore a different class value instead.

**Comment by VachanVY** [comment]
@ianstenbit @innat but when the model predicts `class_probs`, to get `class_id` I'll do `class_id = tf.argmax(class_probs, axis=-1)` then i won't get `-1` class for `no_object`. 

### So, I think the class_id `-1` for `no_object` should be changed to `0`

**Comment by VachanVY** [comment]
@ianstenbit Please think about it and respond, `-1` doesn't occur when we want to predict (while using `argmax`) while `0` occurs. ***setting it `0` is more helpful than `-1`, especially while inference as argmax doesn't give `-1` but can give `0`***

**Comment by ianstenbit** [comment]
`0` is frequently a meaningful class, depending on your dataset. `-1` is not, and the results from a KerasCV model explicitly use `-1` to indicate padding / no object.

I would encourage this use of masking instead of relying on `0` always being the background class -- `-1` is the convention throughout KerasCV for no object / mask
