### ISSUE TITLE
Reduce to shorter namespace

### ISSUE THREAD

**Issue by pure-rgb** [keras-team/keras-cv#2009]
Hello keras-cv team, 

I followed some of the code examples written in keras-cv and some 

While working with the library, I noticed that some namespaces for key methods can be quite long. For example, `keras_cv.bounding_box.convert_format`. I found that the length of the namespace can make the code slightly more cumbersome to write and read. And also it looks like this should be under the  `keras_cv.utils`  API. There are also some other places I found to conflict with another library (i.e. torch).

- `keras_cv.bounding_box.convert_format` -> `keras_cv.utils.bbox.cvt_format`
- `keras_cv.visualization.plot_image_gallery` -> `keras_cv.utils.plot_image`
- `keras_cv.visualization.plot_bounding_box_gallery` -> `keras_cv.utils.plot_bbox`
- `YOLOV8Detector` -> `YOLOV8`
- `keras_cv.ops` ?
- `keras_cv.point_cloud`?
- `keras_cv.keypoint`?
- `keras_cv.training`?
- `keras_cv.bounding_box`?
- `keras_cv.bounding_box_3d`?

It feels natural to seek some of these APIs from the `keras.utils` API. Also, the `bounding box` can be renamed to `bbox` or just box for the sake of brevity. 

```
keras_cv.bounding_box.convert_format(...)
keras_cv.bounding_box.clip_to_image(...)
keras_cv.bounding_box.compute_iou(...)
```

I understand that the length of the namespace can sometimes reflect the structure of the library. However, if there's a way to shorten these paths without losing the underlying logic, I believe it would be a helpful improvement.

**Comment by ianstenbit** [comment]
I see where you're coming from with this -- and I do think that we should consider some changes to namespacing as long as we're consistent with the Keras API. That said, the Keras API does not include abbreviations -- we like to spell out full words because it makes for a more readable API, and the extra letters switching from `convert` to `cvt` doesn't really buy us anything.

That said -- now that we're using `keras_cv_export`, we can export the same symbol as _multiple_ paths! So for example we could say `keras_cv.bounding_box.convert_format` could also be exported as `keras_cv.utils.convert_box_format`.

WRT the `bounding_box` name in particular -- I am pretty indifferent about `bounding_box` vs `box`, and I'm personally happy with exporting as either both or switching to `box`. I'm not aware of why `bounding_box` was chosen initially so I would like to understand that before making the change.

If there are individual example components you'd like to propose a new path for, feel free to open a PR updating the `keras_cv_export` for that symbol.

**Comment by pure-rgb** [comment]
> we like to spell out full words because it makes for a more readable API,

Not really, but it depends. It would be better for keras to be more flexible. It can take an example from another well-established framework, i.e. torch, transformers. TBH, one of my colleagues mentioned disliking tf/keras because of the long naming convention.

>   extra letters switching from convert to cvt doesn't really buy us anything.

The `cvt` here was an example, doesn't have to be this. The main point here is the same. FYI, the `cvt` here was inspired by [opencv](https://docs.opencv.org/3.4/d8/d01/group__imgproc__color__conversions.html#ga397ae87e1288a81d2363b61574eb8cab). Or, if you look at torch for references, [torchvision.ops.box_convert](https://pytorch.org/vision/main/generated/torchvision.ops.box_convert.html)


> That said -- now that we're using keras_cv_export, we can export the same symbol as multiple paths! So for example we could say keras_cv.bounding_box.convert_format could also be exported as keras_cv.utils.convert_box_format

Didn't have any idea about this. But looking at the above example, I think keras should avoid multiple namespaces to achieve the same functionality. The tensorflow has a bad reputation to have multiple namespaces to achieve the same functionality. Please check below, the following APIs, collected from this [source](https://medium.com/geekculture/tensorflow-sad-story-cf8e062d84ba).

[tf.nn.conv2d](https://www.tensorflow.org/api_docs/python/tf/nn/conv2d)
[tf.keras.layers.Conv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D)
[tf.compat.v1.layers.Conv2D](https://www.tensorflow.org/api_docs/python/tf/compat/v1/layers/Conv2D)
[tf.compat.v1.layers.conv2d](https://www.tensorflow.org/api_docs/python/tf/compat/v1/layers/conv2d)
[tf.layers.Conv2D](http://tensorflow.biotecan.com/python/Python_1.8/tensorflow.google.cn/api_docs/python/tf/layers/Conv2D.html)
[tf.raw_ops.Conv2D](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Conv2D)
[tf.contrib.slim.conv2d](https://www.kite.com/python/docs/tensorflow.contrib.slim.conv2d)

That is all.
