### ISSUE TITLE
About YoloV8 License

### ISSUE THREAD

**Issue by heylamourding** [keras-team/keras-cv#2412]
Ultralytics YoloV8 is under AGPL-3.0 license. If I use keras-cv to train a YoloV8 model, can I use it commercially?

**Comment by sachinprasadhs** [comment]
To use `Keras` framework, there is no restriction.

Even from the Ultralytics licensing, it says  it can be used for commercial purpose( look for permission table on top) https://github.com/ultralytics/ultralytics/blob/main/LICENSE

**Comment by heylamourding** [comment]
@sachinprasadhs thanks for reply. Yes. We can use ultralytics commercially but we have to disclose whole project due to AGPL license restriction.

**Comment by heylamourding** [comment]
@innat thanks for reply!

As keras-cv license is Apache 2.0, does mean that we can employ YOLOv8, trained via keras-cv, for commercial purposes without revealing our project details?

**Comment by innat** [comment]
@heylamourding 
Keras implementaiton is done by keras-team (https://github.com/keras-team/keras-cv/pull/1711). So, if you use it, train it from scratch, it's fine. 

About pretrained weight, [here](https://keras.io/api/keras_cv/models/backbones/yolo_v8/#:~:text=Description-,yolo_v8_xs_backbone,An%20extra%20large%20YOLOV8%20backbone%20pretrained%20on%20COCO,-Terms%20%7C%20Privacy), the preset that ends with `coco` are pretrained weight. Now, this I'm not sure how these are generated (cc. @sachinprasadhs ). 

Note, though the model implementation may be same but the performance gap exist in keras-cv yolov8 and official yolo-v8, due to lack of training strategies in keras-cv than official.

**Comment by heylamourding** [comment]
thanks @innat  glad to hear that!
