### ISSUE TITLE
Utility function for efficient image pools 

### ISSUE THREAD

**Issue by artu1999** [keras-team/keras-cv#252]
See 

- https://arxiv.org/pdf/1612.07828.pdf
- https://arxiv.org/pdf/1703.10593.pdf

Image pools are used often in adversarial training to provide the discriminator with some memory about what he got wrong/right before. Having an efficient implementation of this will be very useful as it can be quite a big memory bottleneck during training, especially when using accelerators.

**Comment by LukeWood** [comment]
The KerasCV team is attempting to narrow the package scope in order to more efficiently use our limited resources. As such, we are only accepting contributions directly related to items on the 6 month roadmap for the package.

If you feel this feature could be particularly useful, or would like to contribute it - please feel free to re-open this issue and ping LukeWood, ianstenbit or tanzhenyu

Feel free to read more on the roadmap:
https://github.com/keras-team/keras-cv/blob/master/.github/ROADMAP.md
