### ISSUE TITLE
Mosaic augmentation

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#260]

**Comment by LukeWood** [comment]
used in yolox training.

**Comment by innat** [comment]
@LukeWood It's as first used or introduced in the yolo-v4 paper. 

I've already made a post regarding the opportunity to have both [Object Detection](https://github.com/keras-team/keras-cv/issues/21) and the [Classification task](https://github.com/keras-team/keras-cv/issues/250). Is there any reason why you've opened a new one? Otherwise, it can be closed.

**Comment by LukeWood** [comment]
ah - can close this.
