### ISSUE TITLE
Apply @tf.function to the __call__ method of RandAugment

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#310]

**Comment by bhack** [comment]
Probably it is better to have some interface to control `@tf.function` in the base class: https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_augmentation_pipeline.py

So that we could conditionally control also the pipeline compilation similar to https://github.com/keras-team/keras/issues/16403

**Comment by LukeWood** [comment]
Removed from v0.1 because MOST users will use this in a tf.data pipeline or keras model that automatically does this.

**Comment by LukeWood** [comment]
I do agree a higher level abstraction would be nice though @bhack
