### ISSUE TITLE
Video Data augmentation & Preprocessing Pipelines - Feature Engineering

### ISSUE THREAD

**Issue by Tony363** [keras-team/keras-cv#312]
**B. Video Data Preprocessing Pipelines**

1. Identify key components of pipelines concerning Video as a data point
2. Properly structure a Video loading object that can utilize GPU memory
3. Enable basic Exploratory Data analysis methods for videos embeddings or tensors
4. Video data point visualization
    - How to appropriately visualize videos or the embeddings?
    - Model Error Analysis aids with Videos as data
    
[Proposal link:](https://docs.google.com/document/d/1_xcWXFQjekvtwrhsqaZN03ribcD65-GWyNZ-EgSfJrA/edit?usp=sharing) 
Please comment on proposal

**Comment by LukeWood** [comment]
The KerasCV team is attempting to narrow the package scope in order to more efficiently use our limited resources. As such, we are only accepting contributions directly related to items on the 6 month roadmap for the package.

If you feel this feature could be particularly useful, or would like to contribute it - please feel free to re-open this issue and ping LukeWood, ianstenbit or tanzhenyu

Feel free to read more on the roadmap:
https://github.com/keras-team/keras-cv/blob/master/.github/ROADMAP.md
