### ISSUE TITLE
Jigsaw Distortion

### ISSUE THREAD

**Issue by kartik4949** [keras-team/keras-cv#382]
Move cells within images similar to jigsaw patterns.
![kitty_jigsaw](https://user-images.githubusercontent.com/38289341/165720846-42495c79-650b-46c2-a99f-8d57bf3020bc.jpg)

**Comment by kartik4949** [comment]
https://brunokrinski.github.io/awesome-data-augmentation/
reference

**Comment by ianstenbit** [comment]
This issue is not currently tied to any near-term objectives of KerasCV, so we are closing it for now. If you think this was done in error, or you are interested in adding this feature yourself, please checkout our [README](https://github.com/keras-team/keras-cv/blob/master/README.md) and re-open this issue if it meets the listed criteria.

Thank you! - The KerasCV team
