### ISSUE TITLE
TrivialAugment image augmentation

### ISSUE THREAD

**Issue by innat** [keras-team/keras-cv#413]
**Short Description**

From abstract, 

> ... While existing automatic augmentation methods need to trade off simplicity, cost and performance, we present a most simple baseline, TrivialAugment, that outperforms previous methods for almost free. TrivialAugment is parameter-free and only applies a single augmentation to each image. ...

**Papers**
Paper: TrivialAugment: Tuning-free Yet State-of-the-Art Data Augmentation
https://arxiv.org/abs/2103.10158

**Existing Implementations**
- https://pytorch.org/vision/stable/generated/torchvision.transforms.TrivialAugmentWide.html#torchvision.transforms.TrivialAugmentWide
- https://github.com/automl/trivialaugment

**Other Information**
- (from me, not yet checked thoroughly for a strong feature request.)

**Comment by LukeWood** [comment]
Realistically, I'm not sure we want this given the citation count and usage.

**Comment by bhack** [comment]
As we are and we have already invested enough community resources on KLP I suggest to strictly monitor/evaluate the impact of https://github.com/keras-team/keras-cv/discussions/93#discussioncomment-2540838 before accumulating too much other solutions in the repo.

**Comment by bhack** [comment]
P.s. I've fixed the reference.

**Comment by ianstenbit** [comment]
This issue is not currently tied to any near-term objectives of KerasCV, so we are closing it for now. If you think this was done in error, or you are interested in adding this feature yourself, please checkout our [README](https://github.com/keras-team/keras-cv/blob/master/README.md) and re-open this issue if it meets the listed criteria.

Thank you! - The KerasCV team
