### ISSUE TITLE
Update performance benchmarking script to include a layer with ops that rely on fallbacks for autovectorization

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#455]
https://github.com/tensorflow/tensorflow/issues/56242

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/issues/56242 was not going to importing keras-cv so it is related to Keras only.

I  think some preprocessing layers in Keras with 2.9 was refactored, like KLP layers in Keras-cv, on the new base class acquiring a randomization policy within the batch + vectorized_map (randomize the transformation for every single element in the batch).

Other then for missing converters  I think that the problem often is in that native ops that doesn't support "a batch" of different parameters:
https://github.com/tensorflow/tensorflow/issues/55639

As already exposed with  https://github.com/keras-team/keras-cv/issues/291 on nightly we have the new signature that will expose the root cause of the fallback: 
```python 
def vectorized_map(fn, elems, fallback_to_while_loop=True, warn=True):
```

If you want to really benchmark the performance gap here an in Keras refactored preprocessing layers I suppose what you really want to test is the batch augmentation (with fixed parameter) vs within batch augmentation.

Related:
https://github.com/keras-team/keras-cv/issues/372#issuecomment-1110827256

**Comment by bhack** [comment]
P.s. just to make the history more consistent, for who is landing on this ticket directly, we started the discussion with @qlzh727 3 months ago at https://github.com/keras-team/keras-cv/pull/146.
