### ISSUE TITLE
ResNet34 architecture

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#57]

**Comment by MrinalTyagi** [comment]
Hi. @LukeWood. I would like to add the model to the library.

**Comment by DavidLandup0** [comment]
May I sign up to port ResNet into KerasCV?

**Comment by LukeWood** [comment]
Hey @DavidLandup0 ResNets are included in the library already.  This is specifically ResNet34, a smaller variant!

**Comment by DavidLandup0** [comment]
Whoops, thanks for the clarification! Still, offering to do ResNet34 if it's up for grabs :)

**Comment by LukeWood** [comment]
This is implemented now

**Comment by DavidLandup0** [comment]
@LukeWood are you planning on adding ResNet variants like ResNet-D or ResNet-C? I'd gladly work on those if the basic ones are done :)

**Comment by LukeWood** [comment]
> @LukeWood are you planning on adding ResNet variants like ResNet-D or ResNet-C? I'd gladly work on those if the basic ones are done :)

I have no plans.  Are these ResNets useful compared to modern models?  Typically we want a good reason to add a model; whether it’s performance, widespread use in benchmarks, etc

**Comment by DavidLandup0** [comment]
I have seen some say that they use ResNet-D or C instead of plain ResNets for benchmarks since they address a glaring design issue (ignoring 3/4rds of the input while downsizing). Though, I don't know if this is really enough to make it warranted to implement it.

On another note - some variants are 1-4 line changes, such as DenseNet, DenseNet-C, DenseNet-B and DenseNet-BC (as proposed in the original paper). DenseNet-BC is just DenseNet with bottleneck + transition layers with theta < 1. The `DenseNet` in KerasCV uses a 0.5 theta and a growth rate, so it's a DenseNet-BC implementation.

When variants like these exist, what do you think about including a flag to let users choose between them, with the most commonly one used set as the default? IMO, having the "best" as the default removes guesswork for uses as it does now, but an optional flag can give more flexibility. If it's a 1-5 line change, it might be worth it?

Genuinely not sure what the best solution is - you have much more experience in open source lib development and what users would find useful.
