### ISSUE TITLE
RetinaNet TPU compatibility

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-cv#895]
With evaluate_train_time_metrics=False, .fit() training works, but not validation. Validation will try to XLA-compile the NMS layer which will fail. This is whether COCO metrics are defined as metrics in .compile() or not.

This can be fixed by checking if the metrics list is empty or not, and only tracing NMS when they are in fact empty.

**Comment by bhack** [comment]
As I've contributed the `tf.bincout` bridge coverage in TF some of these issues could be solved by using python range instead of `tf.range`:
https://github.com/tensorflow/tensorflow/issues/56769

See @cheshire
https://github.com/tensorflow/tensorflow/commit/56b2e5a77fda3fa573c2eec86d38a92379508118

The residual issues is that, also with this change, we still have:

`pytest keras_cv/metrics/coco/mean_average_precision_test.py`

`bincount_op.cc:52 : UNIMPLEMENTED: Dynamic reshape is not implemented.
        while evaluating input 1 of Bincount operator as a compile-time constant.`

As the bincount input 1 is a `tf.gather_nd`. I don't know if @cheshire could comment on this:
https://github.com/keras-team/keras-cv/blob/e36de54a3b2ee82bed67858d48cad62409f50a64/keras_cv/metrics/coco/mean_average_precision.py#L250-L266

Instead in recall we have other XLA issues issues (@cheshire):
`pytest keras_cv/metrics/coco/recall_test.py`

```python
_REQUIRES failed at xla_ops.cc:296 : UNIMPLEMENTED: Dynamic degenerated dimension that's not most-minor nor most-major is not supported %reshape.37 = f32[1,1]{1,0} reshape(f32[1,1,1]{2,1,0} %slice.16), metadata={op_type="Unpack" op_name="while_1/while/unstack_1" source_file="/workspaces/keras-cv/keras_cv/bounding_box/iou.py" source_line=75}
```

**Comment by bhack** [comment]
For `UNIMPLEMENTED: Dynamic reshape is not implemented` we can track https://github.com/tensorflow/tensorflow/issues/58051
